import test from 'node:test';
import assert from 'node:assert/strict';
import {estimateAbility,developmentGain} from '../src/models/ability.js';
import {STAR_PROFILES} from '../src/data/starProfiles.js';
import {ALL_MARKETS} from '../src/data/worldMarkets.js';
import {worldPlayers,WORLD_MANIFEST,WORLD_CLUBS,worldCoverage} from '../src/data/packs/world.js';
import {createGame} from '../src/core/game.js';
import {validateSave} from '../src/core/validation.js';
import {migrateSave} from '../src/core/migrations.js';
import {agingDay} from '../src/services/careers.js';
import {playersView} from '../src/features/players.js';
import {databaseView} from '../src/features/database.js';
test('50 distinct market definitions, but coverage explicitly does not claim completeness',()=>{assert.equal(ALL_MARKETS.length,50);assert.equal(WORLD_MANIFEST.populatedMarkets,50);assert.equal(new Set(ALL_MARKETS).size,50);assert.equal(WORLD_MANIFEST.sourceComplete,false);assert.equal(WORLD_MANIFEST.verifiedCurrentRegistration,false);assert(WORLD_MANIFEST.players>20000);assert.equal(worldPlayers(ALL_MARKETS).length,WORLD_MANIFEST.players);});
test('Imported real-name identities are unique; selected markets restrict the pool',()=>{const all=worldPlayers(ALL_MARKETS),eg=worldPlayers(['eg']);assert.equal(new Set(all.map(p=>p.id)).size,all.length);assert(eg.every(p=>p.league==='eg'));assert(eg.length>300);assert(all.every(p=>!p.fictional&&p.sourceUrl===undefined&&provenance(p).sourceUrl?.startsWith('https://')&&provenance(p).sourceLicense==='CC-BY-SA-4.0'));assert(all.some(p=>p.ageEstimated));assert(all.filter(p=>p.ageEstimated).every(p=>!p.birthDate));});
test('Deterministic model is not age-only: roles and individual traits differ',()=>{const a=estimateAbility({key:'player-a',age:26,position:'ST',level:70});assert.deepEqual(a,estimateAbility({key:'player-a',age:26,position:'ST',level:70}));const b=estimateAbility({key:'player-b',age:26,position:'ST',level:70});assert.notDeepEqual(a.attributes,b.attributes);assert(a.attributes.shooting>a.attributes.defending);assert(a.professionalism!==b.professionalism||a.naturalFitness!==b.naturalFitness);});
test('Known-star editorial profiles preserve distinct strengths and remain estimates',()=>{assert(Object.keys(STAR_PROFILES).length>=60);const p=estimateAbility({key:'messi',age:39,position:'AM',star:STAR_PROFILES['Lionel Messi']});assert(p.attributes.passing>p.attributes.pace+20);assert.equal(p.abilityMethod,'editorial-estimate');});
test('Development uses coaching/professionalism/injury and never exceeds potential',()=>{const p={age:20,rating:65,potential:80,professionalism:90,developmentRate:1};assert(developmentGain(p,{coach:85,training:3,minutes:5})>developmentGain(p,{coach:0,training:1}));assert.equal(developmentGain(p,{injured:true}),0);assert.equal(developmentGain({...p,rating:80}),0);});
test('Large fresh careers validate, age and have at least 11 sourced own-club players',()=>{for(const clubId of ['ahly','zamalek','masry','ittihad']){const s=createGame({clubId,database:'world',leagues:ALL_MARKETS});validateSave(s);assert(s.players.filter(p=>p.clubId===clubId).length>=11);assert.equal(s.squadLimit,45);}const s=createGame({database:'world',leagues:ALL_MARKETS});s.date='2026-10-01';agingDay(s);validateSave(s);});
test('Large transfer table renders <=50 rows and filtering sees the entire database',()=>{const s=createGame({database:'world',leagues:ALL_MARKETS});const html=playersView(s,true,{});assert.equal((html.match(/<tr>/g)||[]).length,51);assert(playersView(s,true,{search:'Haaland'}).includes('Haaland'));assert(databaseView().includes('CC BY-SA'));});
test('v2 migration changes schema only, never replaces old players or ratings',()=>{const s=createGame({database:'current'});s.version=2;delete s.squadLimit;const before=s.players.map(p=>[p.id,p.name,p.rating]);const migrated=migrateSave(s);assert.equal(migrated.version,18);assert.deepEqual(migrated.players.map(p=>[p.id,p.name,p.rating]),before);assert.equal(s.version,2);validateSave(migrated);});

test('An actual shipped v0.2-engine fixture migrates without changing identities or finances',async()=>{const {readFile}=await import('node:fs/promises');const old=JSON.parse(await readFile(new URL('./fixtures/actual-v02.json',import.meta.url),'utf8'));const next=migrateSave(old);validateSave(next);assert.equal(old.version,2);assert.equal(next.version,18);assert.deepEqual(next.players.map(p=>[p.id,p.name,p.rating]),old.players.map(p=>[p.id,p.name,p.rating]));assert.equal(next.date,old.date);assert.equal(next.finance.cash,old.finance.cash);});
test('Published birthdays are used while absent DOB remains explicitly modelled',()=>{const p=worldPlayers(ALL_MARKETS);const haaland=p.find(x=>x.nameLatin==='Erling Haaland');assert.equal(haaland.birthDate,'2000-07-21');assert.equal(haaland.age,26);assert.equal(haaland.ageEstimated,false);assert.equal(p.filter(x=>x.ageEstimated).length,WORLD_MANIFEST.unknownBirthDates);const est=p.filter(x=>x.ageEstimated);assert(est.every(x=>x.age>=18&&x.age<=36));const mean=est.reduce((a,x)=>a+x.age,0)/est.length;assert(mean>24&&mean<27,'estimated ages should spread around a realistic mean, got '+mean);assert(new Set(est.map(x=>x.age)).size>10);assert.deepEqual(est.slice(0,50).map(x=>x.age),worldPlayers(ALL_MARKETS).filter(x=>x.ageEstimated).slice(0,50).map(x=>x.age));});

// 0.18 — roster supplement, star profiles, conflict resolution
import {readFileSync} from 'node:fs';
import {provenance} from '../src/models/provenance.js';
const PACK_ROWS=JSON.parse(readFileSync(new URL('../src/data/packs/world/players.json',import.meta.url),'utf8'));
const PACK_CLUBS=JSON.parse(readFileSync(new URL('../src/data/packs/world/clubs.json',import.meta.url),'utf8'));
test('0.18 pack: every editorial star key resolves to an imported row; profiles carry Arabic names, valid positions and bounded ratings',()=>{const wikis=new Set(PACK_ROWS.map(r=>r.wiki).filter(Boolean));const keys=Object.keys(STAR_PROFILES);assert(keys.length>=1000,'star count '+keys.length);assert.deepEqual(keys.filter(k=>!wikis.has(k)),[]);for(const k of keys){const s=STAR_PROFILES[k];assert(/[\u0600-\u06FF]/.test(s.nameAr),k);assert(['GK','CB','RB','LB','DM','CM','AM','RW','LW','ST'].includes(s.position),k);assert(s.rating>=38&&s.rating<=94,k);if(s.potential!==undefined)assert(s.potential>=s.rating,k);}});
test('0.18 pack: star overrides reach the game (Vinícius restored at Real Madrid, Rodri at Barcelona, Mostafa Mohamed as ST) and potential flows through',()=>{const all=worldPlayers(ALL_MARKETS);const clubName=id=>PACK_CLUBS.find(c=>c.id===id)?.name||id;const vini=all.find(p=>p.nameLatin==='Vinícius Júnior');assert(vini);assert.equal(vini.clubName,'Real Madrid CF');assert.equal(vini.rating,90);assert.equal(vini.abilityMethod,'editorial-estimate');const rodri=all.find(p=>p.nameLatin==='Rodri'&&p.clubName==='FC Barcelona');assert(rodri&&rodri.rating===90);const mostafa=all.find(p=>p.nameLatin==='Mostafa Mohamed'&&p.league==='tr');assert(mostafa);assert.equal(mostafa.position,'ST');const cubarsi=all.find(p=>p.nameLatin==='Pau Cubarsí');assert.equal(cubarsi.potential,92);assert.equal(cubarsi.age,19);assert(all.filter(p=>provenance(p).abilityMethod==='editorial-estimate').length>=1000);void clubName;});
test('0.18 pack: manifest counts match rows, ids stay unique, supplemented squads are real and attributed, and methods are recorded per row',()=>{assert.equal(WORLD_MANIFEST.id,'world-wikipedia-20260924-v2');assert.equal(PACK_ROWS.length,WORLD_MANIFEST.players);assert.equal(new Set(PACK_ROWS.map(r=>r.id)).size,PACK_ROWS.length);assert.equal(PACK_ROWS.filter(r=>!r.birthDate).length,WORLD_MANIFEST.unknownBirthDates);assert(WORLD_MANIFEST.unknownBirthDates<7000);assert(WORLD_MANIFEST.clubsWithoutPlayers<=5);assert(WORLD_MANIFEST.supplementedClubs.length>=10);for(const sup of WORLD_MANIFEST.supplementedClubs){const club=PACK_CLUBS.find(c=>c.name===sup.club);assert(club.supplement.sourceUrl.startsWith('https://'+sup.lang+'.wikipedia.org/'));const rows=PACK_ROWS.filter(r=>r.clubId===club.id);assert(rows.length>=11,sup.club);assert(rows.some(r=>r.sourceUrl===club.supplement.sourceUrl));}const methods=new Set(PACK_ROWS.map(r=>r.identityMethod).filter(Boolean));for(const m of ['article','redirect','nationality-name','club-name'])assert(methods.has(m),m);for(const r of PACK_ROWS.filter(r=>r.identityMethod&&r.identityMethod!=='article'&&r.identityMethod!=='redirect'&&r.birthDate)){const age=2026-Number(r.birthDate.slice(0,4));assert(age>=16&&age<=40,r.name+' '+r.birthDate);}assert(PACK_ROWS.every(r=>!r.nameAr||!r.nameAr.includes('(')));});
test('0.18 pack: Smouha (Arabic-edition squad) and the restored Egyptian rows are playable in an Egypt-only career',()=>{const eg=worldPlayers(['eg']);const smouha=eg.filter(p=>p.clubName==='Smouha SC');assert(smouha.length>=18);assert(smouha.every(p=>/[\u0600-\u06FF]/.test(p.name)&&provenance(p).sourceUrl.startsWith('https://ar.wikipedia.org/')));const kabaka=eg.find(p=>p.name==='أحمد خالد كباكا');assert(kabaka&&kabaka.clubName==='Al Ahly SC');const s=createGame({clubId:'ahly',database:'world',leagues:['eg']});validateSave(s);assert(s.players.filter(p=>p.clubName==='Smouha SC').length>=18);assert(s.players.filter(p=>p.ageEstimated).every(p=>p.age>=18&&p.age<=36));});
test('0.18b pack: squad-table birthdays (ar/fr/es Wikipedia) are sourced per row, plausible, counted in the manifest, and lift the Maghreb/Latin markets',()=>{const rows=PACK_ROWS.filter(r=>/^(ar|fr|es)wiki-/.test(r.biographyMethod||''));assert(rows.length>=800,'table birthdays '+rows.length);assert.equal(rows.length,WORLD_MANIFEST.tableBirthdays);assert(WORLD_MANIFEST.squadTablePages>=150);for(const r of rows){assert(/^\d{4}-\d{2}-\d{2}$/.test(r.birthDate),r.name);const age=2026-Number(r.birthDate.slice(0,4));assert(age>=16&&age<=40,r.name+' '+r.birthDate);const host=r.biographyMethod.slice(0,2)+'.wikipedia.org';assert((r.biographyUrl.startsWith('https://'+host+'/w/index.php?title=')&&r.biographyUrl.includes('&oldid='))||(r.qid&&r.biographyUrl==='https://www.wikidata.org/wiki/'+r.qid),r.name+' '+r.biographyUrl);}assert(rows.filter(r=>r.biographyUrl.includes('wikipedia.org')).length>=1500);for(const [league,max] of [['dz',0.05],['tn',0.7],['ma',0.55],['co',0.15],['ar',0.06],['uy',0.06]]){const l=PACK_ROWS.filter(r=>r.league===league);const share=l.filter(r=>!r.birthDate).length/l.length;assert(share<=max,league+' unknown-DOB share '+share.toFixed(2));}const identities=PACK_ROWS.filter(r=>/^(ar|fr|es)wiki-/.test(r.identityMethod||''));assert(identities.length>=100);assert(identities.every(r=>r.qid&&r.qid.startsWith('Q')));});
