import { hash, estimateAbility } from "./ability.js";
import { initializeCareer } from "./player.js";
const NAMES = {
  eg: [
    [
      "محمد",
      "أحمد",
      "محمود",
      "مصطفى",
      "عمر",
      "يوسف",
      "حسن",
      "كريم",
      "زياد",
      "إبراهيم",
      "عبد الرحمن",
      "علي",
      "حسام",
      "طارق",
      "خالد",
      "ياسين",
    ],
    [
      "عبد الله",
      "حسن",
      "إبراهيم",
      "سليمان",
      "منصور",
      "النجار",
      "الشاذلي",
      "حلمي",
      "فتحي",
      "سالم",
      "مرسي",
      "فؤاد",
      "زكريا",
      "عطية",
      "رفعت",
      "المنشاوي",
    ],
  ],
  en: [
    [
      "Oliver",
      "Jack",
      "Harry",
      "George",
      "Charlie",
      "Thomas",
      "James",
      "William",
      "Alfie",
      "Ethan",
      "Samuel",
      "Noah",
      "Isaac",
      "Daniel",
      "Lewis",
      "Adam",
    ],
    [
      "Smith",
      "Jones",
      "Williams",
      "Taylor",
      "Brown",
      "Wilson",
      "Davies",
      "Evans",
      "Robinson",
      "Wright",
      "Walker",
      "Thompson",
      "White",
      "Hughes",
      "Green",
      "Hall",
    ],
  ],
  de: [
    [
      "Lukas",
      "Leon",
      "Felix",
      "Jonas",
      "Niklas",
      "Paul",
      "Max",
      "Florian",
      "David",
      "Timo",
      "Jan",
      "Luca",
    ],
    [
      "Müller",
      "Schmidt",
      "Schneider",
      "Fischer",
      "Weber",
      "Wagner",
      "Becker",
      "Hoffmann",
      "Schulz",
      "Koch",
      "Richter",
      "Wolf",
    ],
  ],
  es: [
    [
      "Diego",
      "Pablo",
      "Álvaro",
      "Javier",
      "Sergio",
      "Adrián",
      "Marcos",
      "Hugo",
      "Mario",
      "Iván",
      "Luis",
      "Daniel",
    ],
    [
      "García",
      "Fernández",
      "López",
      "Martínez",
      "Sánchez",
      "Pérez",
      "Gómez",
      "Ruiz",
      "Díaz",
      "Romero",
      "Torres",
      "Navarro",
    ],
  ],
  fr: [
    [
      "Louis",
      "Hugo",
      "Jules",
      "Lucas",
      "Enzo",
      "Nathan",
      "Gabriel",
      "Antoine",
      "Mathis",
      "Baptiste",
      "Yanis",
      "Adam",
    ],
    [
      "Martin",
      "Bernard",
      "Dubois",
      "Thomas",
      "Robert",
      "Richard",
      "Petit",
      "Durand",
      "Leroy",
      "Moreau",
      "Simon",
      "Laurent",
    ],
  ],
  it: [
    [
      "Luca",
      "Marco",
      "Matteo",
      "Andrea",
      "Lorenzo",
      "Alessandro",
      "Giovanni",
      "Davide",
      "Simone",
      "Riccardo",
      "Federico",
      "Filippo",
    ],
    [
      "Rossi",
      "Russo",
      "Ferrari",
      "Esposito",
      "Bianchi",
      "Romano",
      "Colombo",
      "Ricci",
      "Marino",
      "Greco",
      "Bruno",
      "Gallo",
    ],
  ],
  pt: [
    [
      "João",
      "Diogo",
      "Pedro",
      "Miguel",
      "Tiago",
      "Rafael",
      "André",
      "Gonçalo",
      "Tomás",
      "Rui",
      "Nuno",
      "Afonso",
    ],
    [
      "Silva",
      "Santos",
      "Ferreira",
      "Pereira",
      "Oliveira",
      "Costa",
      "Rodrigues",
      "Martins",
      "Sousa",
      "Fernandes",
      "Gomes",
      "Almeida",
    ],
  ],
  nl: [
    [
      "Daan",
      "Bram",
      "Luuk",
      "Finn",
      "Jesse",
      "Thijs",
      "Lars",
      "Sem",
      "Niels",
      "Tim",
      "Ruben",
      "Jasper",
    ],
    [
      "de Jong",
      "Jansen",
      "de Vries",
      "van Dijk",
      "Bakker",
      "Visser",
      "Smit",
      "Meijer",
      "de Boer",
      "Mulder",
      "de Groot",
      "Bos",
    ],
  ],
  sc: [
    [
      "Liam",
      "Callum",
      "Finlay",
      "Ewan",
      "Jamie",
      "Lewis",
      "Cameron",
      "Ross",
      "Fraser",
      "Craig",
      "Alistair",
      "Scott",
    ],
    [
      "MacDonald",
      "Campbell",
      "Stewart",
      "Robertson",
      "Thomson",
      "Anderson",
      "MacLeod",
      "Murray",
      "Scott",
      "Reid",
      "Ross",
      "Fraser",
    ],
  ],
};
const extra = {
  tr: [
    ["Mehmet", "Emre", "Mustafa", "Can", "Arda", "Kerem"],
    ["Yılmaz", "Kaya", "Demir", "Şahin", "Çelik", "Yıldız"],
  ],
  gr: [
    ["Nikos", "Giorgos", "Dimitris", "Kostas", "Andreas", "Petros"],
    [
      "Papadopoulos",
      "Nikolaidis",
      "Dimitriou",
      "Georgiou",
      "Antoniou",
      "Ioannidis",
    ],
  ],
  dk: [
    ["Mikkel", "Anders", "Rasmus", "Magnus", "Frederik", "Søren"],
    ["Jensen", "Nielsen", "Hansen", "Pedersen", "Andersen", "Christensen"],
  ],
  se: [
    ["Erik", "Johan", "Viktor", "Axel", "Emil", "Oskar"],
    ["Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson", "Lindberg"],
  ],
  no: [
    ["Ole", "Lars", "Sander", "Kristian", "Henrik", "Eirik"],
    ["Hansen", "Johansen", "Olsen", "Larsen", "Berg", "Nilsen"],
  ],
  pl: [
    ["Piotr", "Jakub", "Michał", "Kamil", "Jan", "Paweł"],
    ["Kowalski", "Nowak", "Wiśniewski", "Wójcik", "Kamiński", "Zieliński"],
  ],
  cz: [
    ["Jan", "Petr", "Tomáš", "Lukáš", "Jakub", "Martin"],
    ["Novák", "Svoboda", "Novotný", "Dvořák", "Černý", "Procházka"],
  ],
  hr: [
    ["Luka", "Ivan", "Matej", "Ante", "Josip", "Filip"],
    ["Horvat", "Kovačević", "Babić", "Marić", "Jurić", "Novak"],
  ],
  rs: [
    ["Marko", "Nikola", "Miloš", "Lazar", "Stefan", "Vuk"],
    ["Jovanović", "Petrović", "Nikolić", "Marković", "Đorđević", "Stojanović"],
  ],
  ro: [
    ["Andrei", "Alexandru", "Mihai", "Vlad", "Radu", "Ionuț"],
    ["Popescu", "Ionescu", "Popa", "Dumitrescu", "Stan", "Marin"],
  ],
  ua: [
    ["Andriy", "Oleksandr", "Dmytro", "Maksym", "Vladyslav", "Bohdan"],
    [
      "Kovalenko",
      "Bondarenko",
      "Tkachenko",
      "Melnyk",
      "Kravchenko",
      "Savchenko",
    ],
  ],
  ru: [
    ["Alexei", "Dmitry", "Nikita", "Ivan", "Mikhail", "Artem"],
    ["Ivanov", "Petrov", "Smirnov", "Volkov", "Sokolov", "Kozlov"],
  ],
  hu: [
    ["Bence", "Máté", "Ádám", "Péter", "Dániel", "Balázs"],
    ["Nagy", "Kovács", "Tóth", "Szabó", "Horváth", "Varga"],
  ],
  jp: [
    ["Haruto", "Yuto", "Kaito", "Ren", "Sota", "Daichi"],
    ["Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito"],
  ],
  kr: [
    ["Min-jun", "Seo-jun", "Ji-ho", "Hyun-woo", "Do-yun", "Jun-seo"],
    ["Kim", "Lee", "Park", "Choi", "Jung", "Kang"],
  ],
  cn: [
    ["Wei", "Jun", "Hao", "Lei", "Tao", "Jie"],
    ["Wang", "Li", "Zhang", "Liu", "Chen", "Yang"],
  ],
  sa: [
    ["محمد", "عبد الله", "فهد", "خالد", "سعود", "نواف"],
    ["العتيبي", "القحطاني", "الشهري", "الدوسري", "الغامدي", "الحربي"],
  ],
  qa: [
    ["حسن", "خالد", "جاسم", "محمد", "سالم", "عبد الله"],
    ["المري", "النعيمي", "الكواري", "الهتمي", "الهاجري", "السليطي"],
  ],
  ae: [
    ["علي", "أحمد", "راشد", "سيف", "حمد", "سالم"],
    ["المنصوري", "النعيمي", "الشامسي", "المزروعي", "الكعبي", "البلوشي"],
  ],
  ma: [
    ["يوسف", "ياسين", "أمين", "أيوب", "أنس", "حمزة"],
    ["الإدريسي", "العلوي", "بناني", "المرابط", "الناصري", "الوزاني"],
  ],
  tn: [
    ["محمد", "مهدي", "أيمن", "حمزة", "أنيس", "مالك"],
    ["بن علي", "الطرابلسي", "الجلاصي", "بن سالم", "المثلوثي", "الشابي"],
  ],
  dz: [
    ["ياسين", "إسلام", "مهدي", "سفيان", "بلال", "أنيس"],
    ["بن عيسى", "بن صالح", "بوزيد", "عباس", "منصوري", "بوشارب"],
  ],
  za: [
    ["Thabo", "Sipho", "Lebo", "Kabelo", "Sibusiso", "Andile"],
    ["Mokoena", "Dlamini", "Nkosi", "Molefe", "Khumalo", "Zulu"],
  ],
  in: [
    ["Arjun", "Rahul", "Vikram", "Aditya", "Rohan", "Aman"],
    ["Sharma", "Singh", "Kumar", "Patel", "Das", "Roy"],
  ],
  th: [
    ["Somchai", "Anan", "Niran", "Chai", "Kittipong", "Thanawat"],
    ["Srisuk", "Saetang", "Boonmee", "Thongchai", "Sukjai", "Wongchai"],
  ],
};
Object.assign(NAMES, extra);
for (const [country, base] of Object.entries({
  at: "de",
  ch: "de",
  be: "fr",
  br: "pt",
  ar: "es",
  uy: "es",
  co: "es",
  cl: "es",
  ec: "es",
  py: "es",
  pe: "es",
  bo: "es",
  ve: "es",
  mx: "es",
  us: "en",
  au: "en",
}))
  NAMES[country] = NAMES[base];
const NAT = {
  eg: "EGY",
  en: "ENG",
  de: "GER",
  es: "ESP",
  fr: "FRA",
  it: "ITA",
  pt: "POR",
  nl: "NED",
  sc: "SCO",
  sa: "KSA",
  be: "BEL",
  tr: "TUR",
  gr: "GRE",
  at: "AUT",
  ch: "SUI",
  dk: "DEN",
  se: "SWE",
  no: "NOR",
  pl: "POL",
  cz: "CZE",
  hr: "CRO",
  rs: "SRB",
  ro: "ROU",
  ua: "UKR",
  ru: "RUS",
  hu: "HUN",
  br: "BRA",
  ar: "ARG",
  uy: "URU",
  co: "COL",
  cl: "CHI",
  ec: "ECU",
  py: "PAR",
  pe: "PER",
  bo: "BOL",
  ve: "VEN",
  us: "USA",
  mx: "MEX",
  jp: "JPN",
  kr: "KOR",
  cn: "CHN",
  au: "AUS",
  qa: "QAT",
  ae: "UAE",
  ma: "MAR",
  tn: "TUN",
  dz: "ALG",
  za: "RSA",
  in: "IND",
  th: "THA",
};
const POS = [
  "GK",
  "GK",
  "CB",
  "CB",
  "CB",
  "CB",
  "RB",
  "LB",
  "RB",
  "DM",
  "DM",
  "CM",
  "CM",
  "CM",
  "AM",
  "RW",
  "LW",
  "RW",
  "ST",
  "ST",
  "ST",
  "LW",
  "GK",
  "AM",
];
export function generatedPlayer(
  club,
  index,
  date,
  seed = 84721,
  youth = false,
) {
  const key = club.id + "-" + seed + "-" + index;
  const n = hash(key),
    pool = NAMES[club.country];
  if (!pool)
    throw Error("قاموس أسماء البلد غير متاح؛ لا نستخدم أسماء من بلد آخر.");
  const name =
    pool[0][n % pool[0].length] +
    " " +
    pool[1][Math.floor(n / pool[0].length) % pool[1].length];
  const age = youth ? 16 + (n % 3) : 18 + (n % 17),
    position = POS[index % 24];
  const gem = hash(key + "gem") % 1000 < 25;
  const a = estimateAbility({
    key,
    age,
    position,
    level: club.overall - (youth ? 8 : 0),
  });
  if (gem) {
    a.potential = Math.min(94, a.rating + 20 + (n % 12));
    if (n % 2 === 0) {
      a.rating = Math.min(79, a.rating + 7);
      a.potential = Math.max(a.rating, a.potential);
    }
  }
  const p = {
    id: "gen-" + hash(key).toString(16) + "-" + index,
    name,
    nameLatin: name,
    clubId: club.id,
    clubName: club.name,
    league: club.country,
    position,
    age,
    birthDate: `${Number(date.slice(0, 4)) - age}-01-01`,
    ageEstimated: false,
    ...a,
    foot: n % 5 === 0 ? "يسرى" : "يمنى",
    nationality: NAT[club.country],
    value: Math.round((a.rating - 25) ** 2 * 4500),
    salary: Math.max(
      3000,
      Math.round(((a.rating - 25) ** 2 * 18) / 1000) * 1000,
    ),
    morale: 75,
    fitness: 95,
    contractEnd: `${Number(date.slice(0, 4)) + 2}-06-30`,
    role: "مداورة",
    appearances: 0,
    goals: 0,
    fictional: true,
    generated: true,
    internationalCaps: 0,
    internationalGoals: 0,
    careerInterest: n % 100,
    scoutingConfidence: 20,
  };
  return initializeCareer(p, date);
}
export function generatedSquad(club, date, seed) {
  return Array.from({ length: 24 }, (_, i) =>
    generatedPlayer(club, i, date, seed),
  );
}
